def word_count(str):
    a = str.split()
    b = len(a)
    return b, ' words'
    
print word_count('I love the decision making process a career in finance would involve. I love to take research or data and apply it to a bigger picture in a practical and strategic manner. The competitive atmosphere of a career in finance, also peaks my interest. I love the clear-cut nature of measuring success in the investing and finance industry.') 
print word_count('These core values play a part in every organization or club I have had a leadership role in. An example of this would be the student organization rEDesign, where I currently serve as president.  rEDesign is an education entrepreneurship club where students create projects to improve our education system in a variety of ways from scratch. It is necessary for the Executive Board to consistently have a Positive Team Attitude in order to be productive and continue to increase members while keeping current members involved. As president, I always have to make sure each person is being accountable and working towards their responsibilities or beyond them. I believe the accountability is best maintained by having personal relationships with members of each member of rEDesign. Furthermore, we enable each member to be committed to the club and their project as a whole by having them create their own projects and having myself sit in on a meeting once a month to make sure everything is running smoothly.')
These core values play a part in every organization or club I have had a leadership role in. An example of this would be the student organization rEDesign, where I currently serve as president.  The club at its core is a mix of education and entrepreneurship where students create projects to improve our education system in a variety of ways from scratch. It is necessary for the Executive Board to consistently have a Positive Team Attitude in order to be productive and continue to increase members while keeping current members involved. As president, I always have to make sure each person is being accountable and working towards their responsibilities or beyond them. I believe the accountability is best maintained by having personal relationships with members of each member of rEDesign. Furthermore, we enable each member to be committed to the club and their project as a whole by having them create their own projects and having myself sit in on a meeting once a month to make sure everything is running smoothly. Each of these core values plays a part in how I believe success can be achieved.


I am interested by the decision making process a career in finance would involve. I love to take research or data and apply it to a bigger picture in a practical and strategic manner. I want to be able to look at data and recognize which numbers indicate a future companies success to create more wealth for both parties. The competitive atmosphere of a career in finance, also peaks my interest. I love the clear-cut nature of measuring success in the investment and finance industry. These two factors together make me deeply interested in a career in finance.

I would hope to understand a few aspects of the finance sector. First, I would like to learn how a variety of jobs are done within the sector to find out which one is best for me. Second, I would like to see how a successful firm such as SRR operates and what skills their employees emphasize to better understand what has led to their success. Lastly, I want to learn what the culture at SRR is like and to see if those values align with my own. If I am able to gain all three of these factors during my time within the program, I believe I will have a much better vision for the finance sector, how to succeed in it, and what a strong office culture that facilitates success looks like.